[package]
name = "SimpleRustHypervisor"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9"
buddy_system_allocator = "0.6"
[profile.dev]
panic = "abort"     # 禁用 panic 时的栈展开

[profile.release]
panic = "abort"
